version: '3.8'
services: 
      app:
        build: .
        command:
            - python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/API_REST
        image: app:API_REST 
        container_name: django_container 
        ports:
            - "8000:8000"
        
        depends_on:
            - db
        

      db:
        volumes:  
             - .data/mysql:/var/lib/mysql
        image: mysql:5.7
        container_name: mysql_container
        restart: always
        environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: rest_api
                MYSQL_USER: django
                MYSQL_PASSWORD: django
        ports: 
            - "3306:3306" 
              